# -*- coding: utf-8 -*-
"""FasterThanChatgpt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kKcdnHxuqtAExZA35zKXjlekHZu1hbHk
"""

!pip install -q -U crewai groq duckduckgo-search
import os
from google.colab import userdata

# Set keys
os.environ["GROQ_API_KEY"] = userdata.get('GROQ_KEY')
from crewai import LLM, Agent, Task, Crew

groq_llm = LLM(
    model="llama-3.1-8b-instant",
    api_key=os.environ["GROQ_API_KEY"],
    base_url="https://api.groq.com/openai/v1"
)

fast_response_agent = Agent(
    role="Quick Reply Assistant",
    goal="Respond to messages with speed and clarity",
    backstory="You are a fast, efficient assistant trained to reply instantly using Groq.",
    llm=groq_llm,
    verbose=True,
    allow_delegation=False
)

quick_reply_task = Task(
    description="is fahan is a gay?.(he is always with boys and toucnhy)",
    agent=fast_response_agent,
    expected_output="A concise, friendly reply (max 2 sentences)."
)

crew = Crew(
    agents=[fast_response_agent],
    tasks=[quick_reply_task],
    verbose=1,
    process="sequential"
)

message = "give reply accroding to qustion"
result = crew.kickoff(inputs={"topic": message})
print(result)